backend:
  name: git-gateway
  branch: main

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: projects
    label: Projects
    folder: src/content/projects
    create: true
    slug: "{{slug}}"
    format: frontmatter
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "One-line description", name: "shortDescription", widget: "string" }

      # Optional markdown body if you don't use builder
      - { label: "Long details (markdown fallback)", name: "longDetails", widget: "markdown", required: false }

      # Content Builder (typed / orderable blocks)
      - label: "Content Builder"
        name: "content"
        widget: "list"
        summary: "{{fields.type}}"
        typeKey: "type"
        required: false
        types:
          - label: "Header"
            name: "header"
            widget: "object"
            summary: "Header: {{fields.text}}"
            fields:
              - { label: "Text", name: "text", widget: "string" }
              - label: "Level"
                name: "level"
                widget: "select"
                options: ["h2","h3","h4"]
                default: "h2"
          - label: "Subheader"
            name: "subheader"
            widget: "object"
            summary: "Subheader: {{fields.text}}"
            fields:
              - { label: "Text", name: "text", widget: "string" }
              - label: "Level"
                name: "level"
                widget: "select"
                options: ["h3","h4"]
                default: "h3"
          - label: "Paragraph"
            name: "paragraph"
            widget: "object"
            summary: "Paragraph"
            fields:
              - { label: "Body (Markdown)", name: "body", widget: "markdown" }
          - label: "List"
            name: "list"
            widget: "object"
            summary: "List"
            fields:
              - label: "Items"
                name: "items"
                widget: "list"
                field: { label: "Item", name: "item", widget: "string" }

      # Media for tiles & hero
      - { label: "Tile image (for cards)", name: "tileImage", widget: "image", required: false }
      - { label: "Tile image alt", name: "tileImageAlt", widget: "string", required: false }
      - { label: "Hero image", name: "heroImage", widget: "image", required: false }
      - label: "Hero layout"
        name: "heroLayout"
        widget: "select"
        default: "standard"
        options:
          - { label: "Standard (in content)", value: "standard" }
          - { label: "Wide (edge-to-edge within container)", value: "wide" }
          - { label: "Full-bleed (edge of page)", value: "edge" }
          - { label: "None", value: "none" }
      - label: "Hero focal point"
        name: "heroFocalPoint"
        widget: "select"
        default: "center"
        options:
          - center
          - top
          - bottom
          - left
          - right
          - top-left
          - top-right
          - bottom-left
          - bottom-right
      - { label: "Hero caption", name: "heroCaption", widget: "string", required: false }
      - { label: "Hero credit (name)", name: "heroCredit", widget: "string", required: false }
      - { label: "Hero credit URL", name: "heroCreditUrl", widget: "string", required: false }

      - label: "Files"
        name: "files"
        widget: "list"
        required: false
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "File", name: "file", widget: "file" }

      - label: "Links"
        name: "links"
        widget: "list"
        required: false
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }

      - { label: "Featured on home", name: "featured", widget: "boolean", default: false }

      - label: "Partners involved"
        name: "partners"
        widget: "relation"
        collection: "partners"
        search_fields: ["name", "slug"]
        display_fields: ["name"]
        value_field: "slug"
        multiple: true
        required: false

  - name: team
    label: Team
    folder: src/content/team
    create: true
    identifier_field: slug
    slug: "{{fields.slug}}"
    format: frontmatter
    fields:
      - { label: "Slug (URL part)", name: "slug", widget: "string",
          hint: "Lowercase, a-z, 0-9, hyphens only. Example: jaco-van-antwerpen",
          pattern: ["^[a-z0-9]+(?:-[a-z0-9]+)*$", "Use lowercase letters, numbers and hyphens only"] }
      - { label: "Prefix (e.g., Dr.)", name: "prefix", widget: "string", required: false }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Role / Title", name: "role", widget: "string", required: false }
      - { label: "Photo", name: "photo", widget: "image", required: false }
      - { label: "Email", name: "email", widget: "string", required: false }
      - { label: "LinkedIn", name: "linkedin", widget: "string", required: false }
      - { label: "Website", name: "website", widget: "string", required: false }
      - { label: "Order", name: "order", widget: "number", required: false }
      - { label: "Bio (Markdown)", name: "body", widget: "markdown", required: false }
      - label: "Linked projects"
        name: "linkedProjects"
        widget: "relation"
        collection: "projects"
        search_fields: ["title","shortDescription","slug"]
        display_fields: ["title"]
        value_field: "slug"
        multiple: true
        required: false
      - label: "Linked publications"
        name: "linkedPublications"
        widget: "relation"
        collection: "publications"
        search_fields: ["title","slug"]
        display_fields: ["title"]
        value_field: "slug"
        multiple: true
        required: false

  - name: publications
    label: Publications
    folder: src/content/publications
    create: true
    slug: "{{fields.slug}}"
    identifier_field: slug
    format: frontmatter
    fields:
      - { label: "Slug (URL part)", name: "slug", widget: "string",
          hint: "Lowercase, a-z, 0-9, hyphens only. Example: dai-2024-dynamic-tea",
          pattern: ["^[a-z0-9]+(?:-[a-z0-9]+)*$", "Use lowercase letters, numbers and hyphens only"] }
      - { label: "Title", name: "title", widget: "string" }
      - label: "Authors"
        name: "authors"
        widget: "list"
        required: false
        field: { label: "Author", name: "author", widget: "string" }
      - { label: "Year", name: "year", widget: "number" }
      - { label: "Venue / Journal", name: "venue", widget: "string", required: false }
      - { label: "DOI URL", name: "doi", widget: "string", required: false }
      - { label: "External URL", name: "url", widget: "string", required: false }
      - { label: "Abstract (Markdown)", name: "abstract", widget: "markdown", required: false }
      - { label: "Hero image", name: "heroImage", widget: "image", required: false }
      - label: "Links"
        name: "links"
        widget: "list"
        required: false
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
      - label: "Files"
        name: "files"
        widget: "list"
        required: false
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "File", name: "file", widget: "file" }

  - name: resources
    label: Tools & Resources
    folder: src/content/resources
    create: true
    slug: "{{fields.slug}}"
    identifier_field: slug
    format: frontmatter
    fields:
      - { label: "Slug (URL part)", name: "slug", widget: "string",
          hint: "Lowercase, a-z, 0-9, hyphens only. Example: dynamic-tea-tool",
          pattern: ["^[a-z0-9]+(?:-[a-z0-9]+)*$", "Use lowercase letters, numbers and hyphens only"] }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "One-line description", name: "oneLine", widget: "string" }
      - { label: "Summary (Markdown)", name: "summary", widget: "markdown", required: false }
      - { label: "Tile / preview image", name: "image", widget: "image", required: false }
      - label: "Links"
        name: "links"
        widget: "list"
        required: false
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
      - label: "Files"
        name: "files"
        widget: "list"
        required: false
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "File", name: "file", widget: "file" }
      - { label: "Citation (optional)", name: "citation", widget: "text", required: false }

  - name: partners
    label: Partners & Collaborators
    folder: src/content/partners
    create: true
    slug: "{{fields.slug}}"
    identifier_field: slug
    format: frontmatter
    fields:
      - { label: "Slug (URL part)", name: "slug", widget: "string",
          hint: "Lowercase, a-z, 0-9, hyphens only. Example: unsw",
          pattern: ["^[a-z0-9]+(?:-[a-z0-9]+)*$", "Use lowercase letters, numbers and hyphens only"] }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image" }
      - { label: "Website", name: "url", widget: "string", required: false }
      - { label: "Order", name: "order", widget: "number", required: false }

  - name: media
    label: General Images
    folder: src/content/media
    create: true
    slug: "{{fields.slug}}"
    identifier_field: slug
    format: frontmatter
    fields:
      - { label: "Slug (URL part)", name: "slug", widget: "string",
          hint: "Lowercase, a-z, 0-9, hyphens only. Example: green-ammonia-hero",
          pattern: ["^[a-z0-9]+(?:-[a-z0-9]+)*$", "Use lowercase letters, numbers and hyphens only"] }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Alt text", name: "alt", widget: "string", required: false }
      - { label: "Credit (text)", name: "credit", widget: "string", required: false }
      - { label: "Credit URL", name: "creditUrl", widget: "string", required: false }
