backend:
  name: git-gateway
  branch: main

media_folder: public/uploads
public_folder: /uploads

collections:
  # -----------------------------
  # Projects
  # -----------------------------
  - name: projects
    label: Projects
    folder: src/content/projects
    create: true
    slug: "{{slug}}"
    format: frontmatter
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "One-line description", name: "shortDescription", widget: "string", required: false }
      - { label: "Long details (markdown)", name: "longDetails", widget: "markdown", required: false }

      # Optional content builder (kept compatible)
      - label: "Content Builder"
        name: "content"
        widget: "list"
        required: false
        summary: "{{fields.type}}"
        typeKey: "type"
        types:
          - label: "Header"
            name: "header"
            widget: "object"
            summary: "Header: {{fields.text}}"
            fields:
              - { label: "Text", name: "text", widget: "string" }
              - label: "Level"
                name: "level"
                widget: "select"
                options: ["h2","h3","h4"]
                default: "h2"
          - label: "Paragraph"
            name: "paragraph"
            widget: "object"
            fields:
              - { label: "Body (Markdown)", name: "body", widget: "markdown" }
          - label: "Image"
            name: "image"
            widget: "object"
            fields:
              - { label: "File", name: "src", widget: "image" }
              - { label: "Alt text", name: "alt", widget: "string", required: false }

      # Hero & card images
      - { label: "Hero image", name: "heroImage", widget: "image", required: false }
      - { label: "Hero image alt", name: "heroImageAlt", widget: "string", required: false }

      - { label: "Tile image (for cards)", name: "tileImage", widget: "image", required: false }
      - { label: "Tile image alt", name: "tileImageAlt", widget: "string", required: false }

      # NEW: focal point used by the frontend for cropping in cards
      - label: "Tile image focus"
        name: "tileImageFocus"
        widget: "select"
        required: false
        options:
          - { label: "Center", value: "center" }
          - { label: "Top", value: "top" }
          - { label: "Bottom", value: "bottom" }
          - { label: "Left", value: "left" }
          - { label: "Right", value: "right" }
          - { label: "Top-left", value: "top-left" }
          - { label: "Top-right", value: "top-right" }
          - { label: "Bottom-left", value: "bottom-left" }
          - { label: "Bottom-right", value: "bottom-right" }
        default: "center"

      # Attachments & external links
      - label: "Files"
        name: "files"
        widget: "list"
        required: false
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "File", name: "file", widget: "file" }

      - label: "Links"
        name: "links"
        widget: "list"
        required: false
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }

      - { label: "Completed (date)", name: "completed", widget: "datetime", required: false }
      - { label: "Featured on home", name: "featured", widget: "boolean", default: false }

      # UPDATED: ordered, draggable partner list
      - label: "Partners involved"
        name: "partners"
        widget: "list"
        required: false
        summary: "{{fields.partner}}"
        fields:
          - label: "Partner"
            name: "partner"
            widget: "relation"
            collection: "partners"
            search_fields: ["name", "slug"]
            display_fields: ["name"]
            value_field: "slug"

  # -----------------------------
  # Team
  # -----------------------------
  - name: team
    label: Team
    folder: src/content/team
    create: true
    slug: "{{slug}}"
    format: frontmatter
    fields:
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Prefix (Dr., Prof., etc.)", name: "prefix", widget: "string", required: false }
      - { label: "Full name", name: "name", widget: "string" }
      - { label: "Role/Title", name: "role", widget: "string", required: false }
      - { label: "Headshot", name: "photo", widget: "image", required: false }
      - { label: "Email", name: "email", widget: "string", required: false }
      - { label: "LinkedIn URL", name: "linkedin", widget: "string", required: false }
      - { label: "Website", name: "website", widget: "string", required: false }
      - { label: "Short bio (optional)", name: "longSummary", widget: "text", required: false }
      - { label: "Body (Markdown)", name: "body", widget: "markdown", required: false }
      - { label: "Order", name: "order", widget: "number", required: false }

      - label: "Linked Projects"
        name: "linkedProjects"
        widget: "relation"
        collection: "projects"
        search_fields: ["title", "slug"]
        display_fields: ["title"]
        value_field: "slug"
        multiple: true
        required: false

      - label: "Linked Publications"
        name: "linkedPublications"
        widget: "relation"
        collection: "publications"
        search_fields: ["title", "slug"]
        display_fields: ["title"]
        value_field: "slug"
        multiple: true
        required: false

  # -----------------------------
  # Publications (minimal)
  # -----------------------------
  - name: publications
    label: Publications
    folder: src/content/publications
    create: true
    slug: "{{slug}}"
    format: frontmatter
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Authors", name: "authors", widget: "string", required: false }
      - { label: "Year", name: "year", widget: "number", required: false }
      - { label: "Journal/Outlet", name: "journal", widget: "string", required: false }
      - { label: "DOI", name: "doi", widget: "string", required: false }
      - { label: "URL", name: "url", widget: "string", required: false }
      - { label: "Abstract", name: "body", widget: "markdown", required: false }

  # -----------------------------
  # Resources (kept simple)
  # -----------------------------
  - name: resources
    label: Resources
    folder: src/content/resources
    create: true
    slug: "{{slug}}"
    format: frontmatter
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown", required: false }

  # -----------------------------
  # Partners
  # -----------------------------
  - name: partners
    label: Collaborators & Partners
    folder: src/content/partners
    create: true
    slug: "{{slug}}"
    format: frontmatter
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Website URL", name: "url", widget: "string", required: false }
      - { label: "Logo", name: "logo", widget: "image" }
      - { label: "Order", name: "order", widget: "number", required: false }

  # -----------------------------
  # General image bucket
  # -----------------------------
  - name: media
    label: General Images
    folder: src/content/media
    create: true
    slug: "{{title}}"
    format: frontmatter
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Alt text", name: "alt", widget: "string", required: false }
      - { label: "Credit (text)", name: "credit", widget: "string", required: false }
      - { label: "Credit URL", name: "creditUrl", widget: "string", required: false }
