backend:
  name: git-gateway
  branch: main

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: projects
    label: Projects
    folder: src/content/projects
    create: true
    slug: "{{slug}}"
    format: frontmatter
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "One-line description", name: "shortDescription", widget: "string" }

      # Nicer fallback if you don't want to use the builder
      - { label: "Long details (markdown fallback)", name: "longDetails", widget: "markdown", required: false }

      # Content Builder (orderable blocks)
      - label: "Content Builder"
        name: "content"
        widget: "list"
        summary: "{{fields.type}}"
        typeKey: "type"
        required: false
        types:
          - label: "Header"
            name: "header"
            widget: "object"
            summary: "Header: {{fields.text}}"
            fields:
              - { label: "Text", name: "text", widget: "string" }
              - label: "Level"
                name: "level"
                widget: "select"
                options: ["h2","h3","h4"]
                default: "h2"

          - label: "Subheader"
            name: "subheader"
            widget: "object"
            summary: "Subheader: {{fields.text}}"
            fields:
              - { label: "Text", name: "text", widget: "string" }
              - label: "Level"
                name: "level"
                widget: "select"
                options: ["h3","h4"]
                default: "h3"

          - label: "Paragraph"
            name: "paragraph"
            widget: "object"
            summary: "Paragraph"
            fields:
              - { label: "Body (Markdown)", name: "body", widget: "markdown" }

          - label: "List"
            name: "list"
            widget: "object"
            summary: "List ({{fields.style}})"
            fields:
              - label: "Style"
                name: "style"
                widget: "select"
                options:
                  - { label: "Bulleted", value: "ul" }
                  - { label: "Numbered", value: "ol" }
                default: "ul"
              - label: "Items"
                name: "items"
                widget: "list"
                field: { label: "Item", name: "item", widget: "string" }

          - label: "Link"
            name: "link"
            widget: "object"
            summary: "Link: {{fields.label}}"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }

          - label: "File"
            name: "file"
            widget: "object"
            summary: "File: {{fields.label}}"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "File", name: "file", widget: "file" }

      - { label: "Hero image", name: "heroImage", widget: "image", required: false }
      - { label: "Tile image (grid card)", name: "tileImage", widget: "image", required: false }
      - { label: "Completed (free text)", name: "completed", widget: "string", required: false }
      - { label: "Featured?", name: "featured", widget: "boolean", required: false, default: false }
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
        field: { label: "Tag", name: "tag", widget: "string" }

      # Keep existing bottom sections for compatibility
      - label: "Files (bottom section)"
        name: "files"
        widget: "list"
        required: false
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "File", name: "file", widget: "file" }

      - label: "Links (bottom section)"
        name: "links"
        widget: "list"
        required: false
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }

  - name: resources
    label: "Tools & Resources"
    folder: src/content/resources
    create: true
    slug: "{{slug}}"
    format: frontmatter
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "One-line description", name: "oneLine", widget: "string" }
      - { label: "Summary", name: "summary", widget: "text", required: false }
      - label: "Files"
        name: "files"
        widget: "list"
        required: false
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "File", name: "file", widget: "file" }
      - label: "Links"
        name: "links"
        widget: "list"
        required: false
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
      - { label: "Citation", name: "citation", widget: "text", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
