backend:
  name: git-gateway
  branch: main

media_folder: public/uploads
public_folder: /uploads

collections:
  # -----------------------------
  # Projects
  # -----------------------------
  - name: projects
    label: Projects
    folder: src/content/projects
    create: true
    slug: "{{slug}}"
    format: frontmatter
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "One-line description", name: "shortDescription", widget: "string" }
      - { label: "Long details (markdown fallback)", name: "longDetails", widget: "markdown", required: false }

      - label: "Content Builder"
        name: "content"
        widget: "list"
        summary: "{{fields.type}}"
        typeKey: "type"
        required: false
        types:
          - label: "Header"
            name: "header"
            widget: "object"
            summary: "Header: {{fields.text}}"
            fields:
              - { label: "Text", name: "text", widget: "string" }
              - label: "Level"
                name: "level"
                widget: "select"
                options: ["h2", "h3", "h4"]
                default: "h3"

          - label: "Paragraph"
            name: "paragraph"
            widget: "object"
            summary: "Paragraph"
            fields:
              - { label: "Text (Markdown)", name: "body", widget: "markdown" }

          - label: "Image"
            name: "image"
            widget: "object"
            summary: "Image: {{fields.alt}}"
            fields:
              - { label: "Image", name: "src", widget: "image" }
              - { label: "Alt text", name: "alt", widget: "string" }
              - { label: "Caption", name: "caption", widget: "string", required: false }
              - { label: "Credit (text)", name: "credit", widget: "string", required: false }
              - { label: "Credit URL", name: "creditUrl", widget: "string", required: false }
              - label: "Alignment"
                name: "align"
                widget: "select"
                options: ["left", "center", "right"]
                default: "center"

          - label: "Quote"
            name: "quote"
            widget: "object"
            summary: "Quote: {{fields.text}}"
            fields:
              - { label: "Text", name: "text", widget: "text" }
              - { label: "Attribution", name: "attribution", widget: "string", required: false }

      # Hero & metadata
      - { label: "Featured on home", name: "featured", widget: "boolean", default: false }
      - { label: "Order", name: "order", widget: "number", required: false }
      - { label: "Last updated", name: "lastUpdated", widget: "datetime", required: false }
      - { label: "Published", name: "published", widget: "boolean", default: true }

      # Attachments & external links
      - label: "Files"
        name: "files"
        widget: "list"
        required: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "File", name: "file", widget: "file" }
          - { label: "Description", name: "description", widget: "string", required: false }

      - label: "Links"
        name: "links"
        widget: "list"
        required: false
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }

      # UPDATED: ordered, draggable partner list
      - label: "Partners involved"
        name: "partners"
        widget: "list"
        required: false
        summary: "{{fields.partner}}"
        fields:
          - label: "Partner"
            name: "partner"
            widget: "relation"
            collection: "partners"
            search_fields: ["name", "slug"]
            value_field: "{{slug}}"
            display_fields: ["name"]

  # -----------------------------
  # Team
  # -----------------------------
  - name: team
    label: Team
    folder: src/content/team
    create: true
    slug: "{{slug}}"
    format: frontmatter
    fields:
      - { label: "Full name", name: "name", widget: "string" }
      - { label: "Role/Title", name: "role", widget: "string", required: false }
      - { label: "Headshot", name: "photo", widget: "image", required: false }
      - { label: "Email", name: "email", widget: "string", required: false }
      - { label: "LinkedIn URL", name: "linkedin", widget: "string", required: false }
      - { label: "Website", name: "website", widget: "string", required: false }
      - { label: "Short bio (optional)", name: "longSummary", widget: "text", required: false }
      - { label: "Body (Markdown)", name: "body", widget: "markdown", required: false }
      - { label: "Order", name: "order", widget: "number", required: false }

      - label: "Linked Projects"
        name: "linkedProjects"
        widget: "relation"
        collection: "projects"
        search_fields: ["title", "slug"]
        value_field: "{{slug}}"
        display_fields: ["title"]
        multiple: true
        required: false

  # -----------------------------
  # Publications
  # -----------------------------
  - name: publications
    label: Publications
    folder: src/content/publications
    create: true
    slug: "{{slug}}"
    format: frontmatter
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Authors", name: "authors", widget: "string", required: false }
      - { label: "Journal / Venue", name: "venue", widget: "string", required: false }
      - { label: "Year", name: "year", widget: "number", required: false }
      - { label: "PDF", name: "pdf", widget: "file", required: false }
      - { label: "DOI / URL", name: "url", widget: "string", required: false }
      - { label: "Order", name: "order", widget: "number", required: false }

  # -----------------------------
  # Resources
  # -----------------------------
  - name: resources
    label: Resources
    folder: src/content/resources
    create: true
    slug: "{{slug}}"
    format: frontmatter
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Summary", name: "summary", widget: "text", required: false }
      - { label: "File", name: "file", widget: "file", required: false }
      - { label: "URL", name: "url", widget: "string", required: false }
      - { label: "Order", name: "order", widget: "number", required: false }

  # -----------------------------
  # Partners
  # -----------------------------
  - name: partners
    label: Collaborators & Partners
    folder: src/content/partners
    create: true
    slug: "{{slug}}"
    format: frontmatter
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Website URL", name: "url", widget: "string", required: false }
      - { label: "Logo", name: "logo", widget: "image" }
      - { label: "Affiliation (toggle)", name: "affiliate", widget: "boolean", default: false, required: false }
      - { label: "Order", name: "order", widget: "number", required: false }

  # -----------------------------
  # General image bucket
  # -----------------------------
  - name: media
    label: General Images
    folder: src/content/media
    create: true
    slug: "{{title}}"
    format: frontmatter
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Alt text", name: "alt", widget: "string", required: false }
      - { label: "Credit (text)", name: "credit", widget: "string", required: false }
      - { label: "Credit URL", name: "creditUrl", widget: "string", required: false }
